name: Docker Image build and push

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  path-context:
    name: Build and push
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: tobsa13/testaction/test
        tag_with_sha: true
        tag_with_ref: true